### ISSUE TITLE
Certificate info

### ISSUE THREAD

**Issue by Rocky5** [BttrDrgn/XVVVVX#1]
Would you be able to add the following to your project file please?

TitleID = 0x58565658 (this is just XVVX in hex)
Title = XVVVVX

This just means I don need a to make an Override_TitleID.bin for the artwork installer.
( and anything else that uses titleids )

**Comment by BttrDrgn** [comment]
Fixed it. Thank you! If it is incorrect when I push let me know.

**Comment by Rocky5** [comment]
Cheers, much appreciated.
